### ISSUE TITLE
Spike: Migrate from WPF to Avalonia UI

### ISSUE THREAD

**Issue by Haato3o** [HunterPie/HunterPie#393]

**Comment by CartoonFan** [comment]
I'm aware that Proton/Wine is unsupported, but I ran into the issue where WPF shows black borders around the widgets (instead of transparency), and I'm wondering if Avalonia UI might be able to fix this particular issue. Avalonia's supposed to be cross-platform, so I'm a bit optimistic, but I'm wondering how hyped I should be, if that makes sense.

Sorry if all this sounds really chaotic :sweat_smile: 

Thanks for your hard work! :+1:

**Comment by LittleFinix** [comment]
I'm currently working on porting HunterPie to Avalonia/Linux. I've already rewritten the interface such that it compiles and displays the main window and widgets, though things still look a bit wonky.

There are some general problems with porting from WPF to Avalonia. Particularly anything involving animations and data triggers has to be rewritten.

Here's a screenshot of HunterPie running on my Linux Mint
![image](https://github.com/HunterPie/HunterPie/assets/3407997/3115859b-b89e-429e-bd9a-4d598e12918a)

If you're interested, I could upload the fork already. Currently I'm just working on it whenever I have the time.

**Comment by CartoonFan** [comment]
> I'm currently working on porting HunterPie to Avalonia/Linux. I've already rewritten the interface such that it compiles and displays the main window and widgets, though things still look a bit wonky.
> 
> There are some general problems with porting from WPF to Avalonia. Particularly anything involving animations and data triggers has to be rewritten.
> 
> Here's a screenshot of HunterPie running on my Linux Mint ![image](https://user-images.githubusercontent.com/3407997/262130490-3115859b-b89e-429e-bd9a-4d598e12918a.png)
> 
> If you're interested, I could upload the fork already. Currently I'm just working on it whenever I have the time.

The screenshot looks really good! I think uploading the fork would be helpful, both for myself and the community, so if it's not too much trouble...please? :pray: 

Thanks!

**Comment by Haato3o** [comment]
> There are some general problems with porting from WPF to Avalonia. Particularly anything involving animations and data triggers has to be rewritten.

Well, HunterPie is pretty heavy on animations and data triggers, so that might be some work


> If you're interested, I could upload the fork already. Currently I'm just working on it whenever I have the time.

That would be great

**Comment by LittleFinix** [comment]
> How did you get it to run on Linux though? Did you implement the IMemory for linux using the native linux API for reading memory?

Exactly, among other things. Ultimately the process memory is just a file in /proc/$pid/mem, so reading it is particularly easy.

> Well, HunterPie is pretty heavy on animations and data triggers, so that might be some work

Yeah, currently I've mostly just removed the animations.

As for the data triggers:
They don't exist in Avalonia. Instead I've been implementing them as pseudo classes and classes as appropriate.


It's already late, so I'll be uploading it tomorrow. Currently I'm taking the Linux version out for a test drive with some friends.

**Comment by LittleFinix** [comment]
I've created the fork here https://github.com/LittleFinix/HunterPie/commits/main
I also got some more features working since yesterday.

I also need to clean up some of the code and fixup and write proper commits. It's not really fork worthy as is, aside from the broken features. I'll write up something about the changes I've made and what still needs to be done when I have the time.

**Comment by LittleFinix** [comment]
Some notes:

- I only own World and have only tested it there
- Most widgets, except the Player HUD and Monster Health are broken.
- Some views are unavailable, such as the self-updater, profile, and login
- The settings panel is only somewhat functional.
- Hotkeys aren't working properly
- Widget positions are now relative to the primary screen (though the idea is to make them relative to the game window)
- The localization is broken in some parts.

**Comment by LittleFinix** [comment]
I've also noticed that Avalonia doesn't seem to play nice with DrawingImage. The transforms and clipping aren't working properly, so the Image ends up in a far too large viewbox. When the Image is then scaled down to be displayed, the image ends up as just a few pixels in the bottom right corner.

DrawingImage also can't (currently) be used as an OpacityMask, breaking most usages of Icons. Making them into Image Controls runs into the aforementioned problem.

**Comment by MeikelLP** [comment]
@LittleFinix are still working on this? I'd love to see it happen so I can use it on my steamdeck too.

**Comment by LittleFinix** [comment]
> @LittleFinix are still working on this? I'd love to see it happen so I can use it on my steamdeck too.

I haven't worked on it since October, but I had a friend run it on his SteamDeck. Sadly it didn't work on there as the widgets were not rendered correctly.

Progress-wise it's mostly functional, except the damage graph, most icons and any widgets relating to MHR.

**Comment by LittleFinix** [comment]
I also don't have a SteamDeck to try it out on, so debugging is rather cumbersome.

**Comment by MeikelLP** [comment]
> I also don't have a SteamDeck to try it out on, so debugging is rather cumbersome.

Wouldn't a simple SteamOS VM/bare metal machine be enough to test?

**Comment by LittleFinix** [comment]
I'll try it out tomorrow. For now I have merged the upstream branch and fixed it up. If you download the dotnet SDK you can also try it out yourself.

**Comment by MeikelLP** [comment]
@LittleFinix it does work on Linux/SteamOS however it does not overlay over the game:
![1280-800-max](https://github.com/HunterPie/HunterPie/assets/11669846/db7f5bcf-d828-4c88-a523-5d9841e8defa)

Also for it to work properly it would be required to launch the app previously to the game itself via Steam. How can that be archived? Maybe register HunterPie as non-Steam game and launch it which then launches Monster Hunter?

**Comment by Superredstone** [comment]
Hi, how can i compile HunterPi on Linux? I searched how to compile sln projects but I didn't find anything usefull

**Comment by LittleFinix** [comment]
> Hi, how can i compile HunterPi on Linux? I searched how to compile sln projects but I didn't find anything usefull

You can download the dotnet install script here: <https://dotnet.microsoft.com/en-us/download/dotnet/scripts>
run it with `./dotnet-install.sh --channel 6.0`

Then go into the cloned repository and run `dotnet run --project ./HunterPie`

**Comment by Superredstone** [comment]
> > Hi, how can i compile HunterPi on Linux? I searched how to compile sln projects but I didn't find anything usefull
> 
> You can download the dotnet install script here: <https://dotnet.microsoft.com/en-us/download/dotnet/scripts>
> run it with `./dotnet-install.sh --channel 6.0`
> 
> Then go into the cloned repository and run `dotnet run --project ./HunterPie`

Thank you

**Comment by LittleFinix** [comment]
If @Haato3o agrees I could provide experimental binaries for Linux in my forked repository

**Comment by MeikelLP** [comment]
@LittleFinix Well you don't run games from desktop on the Steamdeck but from SteamOS UI - otherwise u have terrible performance (like in my test). Thus I cannot just start another program after I started MH.

The game is in borderless window mode. However I just saw black bloxes - after refocusing the game they disappeared.

@Superredstone I compiled the game from my Windows machine with .NET 8

```sh
dotnet publish -r linux-x64 --self-contained -p:PublishReadyToRun=true -p:PublishAot=true -c Release
```

**Comment by LittleFinix** [comment]
> @LittleFinix Well you don't run games from desktop on the Steamdeck but from SteamOS UI - otherwise u have terrible performance (like in my test). Thus I cannot just start another program after I started MH.
I see... I'll take a look at that later.

> The game is in borderless window mode. However I just saw black bloxes - after refocusing the game they disappeared.
This is what we experienced when my friend tried it on his SteamDeck. In the screenshot you posted it does work though, is this just because HunterPie was focused?

**Comment by MeikelLP** [comment]
Most likely. However I couldn't get it to be on top again so I don't know for sure

**Comment by Haato3o** [comment]
> If @Haato3o agrees I could provide experimental binaries for Linux in my forked repository

Sure

**Comment by Superredstone** [comment]
When i try running @LittleFinix version of HunterPie i get this error: 
```
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type HunterPie.Core.Client.Configuration.Versions.VersionedConfig. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path '', line 1, position 2.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader, JsonObjectContract, JsonProperty, JsonProperty, String, Boolean&) + 0x1a6
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader, Type, JsonContract, JsonProperty, JsonContainerContract, JsonProperty, Object) + 0x2cf
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader, Type, JsonContract, JsonProperty, JsonContainerContract, JsonProperty, Object) + 0x9e
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader, Type, Boolean) + 0x25f
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader, Type) + 0x100
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String, Type, JsonSerializerSettings) + 0x91
   at HunterPie.Internal.Initializers.ClientConfigMigrationInitializer.ReadSettingsAs[T](Type) + 0x93
   at HunterPie.Internal.Initializers.ClientConfigMigrationInitializer.Init() + 0x30
   at HunterPie.Internal.InitializerManager.<Initialize>d__2.MoveNext() + 0xa3
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xbe
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4e
   at HunterPie.App.<Initialize>d__8.MoveNext() + 0xcb
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x1c
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state) + 0x28
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore() + 0x188
   at Avalonia.Threading.DispatcherOperation.Execute() + 0x72
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation) + 0x5f
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean) + 0xa0
   at Avalonia.Threading.Dispatcher.Signaled() + 0x3e
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() + 0x5d
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken) + 0x250
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl) + 0xff
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame) + 0xb7
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken) + 0x10c
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[]) + 0x159
   at HunterPie!<BaseAddress>+0x12388cc
```

**Comment by LittleFinix** [comment]
@Superredstone, it's an issue with the settings migrator, not sure what exactly. If you backup your settings and remove them from the config folder it should work.

**Comment by Melechtna** [comment]
> @Superredstone, it's an issue with the settings migrator, not sure what exactly. If you backup your settings and remove them from the config folder it should work.

```
Unhandled exception. System.InvalidOperationException: Could not create glyphTypeface.
   at Avalonia.Media.Typeface.get_GlyphTypeface()
   at Avalonia.Rendering.Composition.Compositor.get_DiagnosticTextRenderer()
   at Avalonia.Rendering.Composition.Compositor.CreateCompositionTarget(Func`1 surfaces)
   at Avalonia.Rendering.Composition.CompositingRenderer..ctor(IRenderRoot root, Compositor compositor, Func`1 surfaces)
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl)
   at Avalonia.Controls.Window..ctor(IWindowImpl impl)
   at Avalonia.Controls.Window..ctor()
   at HunterPie.MainWindow..ctor() in /home/melechtna/src/HunterPie/HunterPie/MainWindow.axaml.cs:line 34
   at HunterPie.App.<>c.<Initialize>b__8_0() in /home/melechtna/src/HunterPie/HunterPie/App.axaml.cs:line 68
   at Avalonia.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at Avalonia.Threading.Dispatcher.Invoke[TResult](Func`1 callback)
   at HunterPie.App.Initialize() in /home/melechtna/src/HunterPie/HunterPie/App.axaml.cs:line 68
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at HunterPie.Program.Main(String[] args) in /home/melechtna/src/HunterPie/HunterPie/Program.cs:line 18
   ```
   This is what I get now
